satchmo/apps/l10n/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^setlang/$', 'django.views.i18n.set_language', {}, 'satchmo_set_language'),
)

satchmo/apps/satchmo_store/accounts/urls.py
"""
URLConf for Django user registration.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/accounts/'.

"""
from django.conf.urls.defaults import *
from livesettings import config_value

# extending the urls in contacts
from satchmo_store.contact.urls import urlpatterns
from satchmo_utils.signals import collect_urls
from satchmo_store import accounts

# Activation keys get matched by \w+ instead of the more specific
# [a-fA-F0-9]+ because a bad activation key should still get to the view;
# that way it can return a sensible "invalid key" message instead of a
# confusing 404.
urlpatterns += patterns('satchmo_store.accounts.views',
    (r'^activate/(?P<activation_key>\w+)/$', 'activate', {}, 'registration_activate'),
    (r'^login/$', 'emaillogin', {'template_name': 'registration/login.html'}, 'auth_login'),
    (r'^logout/$', 'shop_logout', {}, 'auth_logout'),
    (r'^register/$', 'register', {}, 'registration_register'),
    (r'^secure/login/$', 'emaillogin', {'SSL' : True, 'template_name': 'registration/login.html'}, 'auth_secure_login'),    
)

verify = (config_value('SHOP', 'ACCOUNT_VERIFICATION') == 'EMAIL')

urlpatterns += patterns('django.views.generic',
    (r'^register/complete/$', 'simple.direct_to_template',
        {'template': 'registration/registration_complete.html',
        'extra_context': {'verify': verify }}, 
        'registration_complete'),
)

#Dictionary for authentication views
password_reset_dict = {
    'template_name': 'registration/password_reset_form.html',
    'email_template_name': 'registration/password_reset.txt',
}

# the "from email" in password reset is problematic... it is hard coded as None
urlpatterns += patterns('django.contrib.auth.views',
    (r'^password_reset/$', 'password_reset', password_reset_dict, 'auth_password_reset'),
    (r'^password_reset/done/$', 'password_reset_done', {'template_name':'registration/password_reset_done.html'}, 'auth_password_reset_done'),
    (r'^password_change/$', 'password_change', {'template_name':'registration/password_change_form.html'}, 'auth_password_change'),
    (r'^password_change/done/$', 'password_change_done', {'template_name':'registration/password_change_done.html'}, 'auth_change_done'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'password_reset_confirm'),
    (r'^reset/done/$', 'password_reset_complete'),
)

collect_urls.send(sender=accounts, patterns=urlpatterns)

satchmo/projects/large/urls.py
from django.conf.urls.defaults import *

from satchmo_store.urls import urlpatterns

urlpatterns += patterns('',
    (r'test/', include('large.localsite.urls'))
)

satchmo/projects/simple/urls.py
from django.conf.urls.defaults import *

from satchmo_store.urls import urlpatterns

urlpatterns += patterns('',
    (r'test/', include('simple.localsite.urls'))
)

satchmo/apps/satchmo_store/accounts/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _, ugettext
from satchmo_store.accounts.mail import send_welcome_email
from livesettings import config_value
from satchmo_store.contact.forms import ContactInfoForm
from satchmo_store.contact.models import AddressBook, PhoneNumber, Contact
from l10n.models import Country
from satchmo_utils.unique_id import generate_id

import logging
import signals

log = logging.getLogger('accounts.forms')

class EmailAuthenticationForm(AuthenticationForm):
    """Authentication form with a longer username field."""
    
    def __init__(self, *args, **kwargs):
        
        super(EmailAuthenticationForm, self).__init__(*args, **kwargs)
        username = self.fields['username']
        username.max_length = 75
        username.widget.attrs['maxlength'] = 75

class RegistrationForm(forms.Form):
    """The basic account registration form."""
    title = forms.CharField(max_length=30, label=_('Title'), required=False)
    email = forms.EmailField(label=_('Email address'),
        max_length=75, required=True)
    password2 = forms.CharField(label=_('Password (again)'),
        max_length=30, widget=forms.PasswordInput(), required=True)
    password1 = forms.CharField(label=_('Password'),
        max_length=30, widget=forms.PasswordInput(), required=True)
    first_name = forms.CharField(label=_('First name'),
        max_length=30, required=True)
    last_name = forms.CharField(label=_('Last name'),
        max_length=30, required=True)
    next = forms.CharField(max_length=100, required=False, widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        self.contact = None
        super(RegistrationForm, self).__init__(*args, **kwargs)

    newsletter = forms.BooleanField(label=_('Newsletter'),
        widget=forms.CheckboxInput(), required=False)

    def clean_password1(self):
        """Enforce that password and password2 are the same."""
        p1 = self.cleaned_data.get('password1')
        p2 = self.cleaned_data.get('password2')
        if not (p1 and p2 and p1 == p2):
            raise forms.ValidationError(
                ugettext("The two passwords do not match."))

        # note, here is where we'd put some kind of custom
        # validator to enforce "hard" passwords.
        return p1

    def clean_email(self):
        """Prevent account hijacking by disallowing duplicate emails."""
        email = self.cleaned_data.get('email', None)
        if email and User.objects.filter(email__iexact=email).count() > 0:
            raise forms.ValidationError(
                ugettext("That email address is already in use."))

        return email

    def save(self, request=None, **kwargs):
        """Create the contact and user described on the form.  Returns the
        `contact`.
        """
        if self.contact:
            log.debug('skipping save, already done')
        else:
            self.save_contact(request)
        return self.contact

    def save_contact(self, request):
        log.debug("Saving contact")
        data = self.cleaned_data
        password = data['password1']
        email = data['email']
        first_name = data['first_name']
        last_name = data['last_name']
        username = generate_id(first_name, last_name, email)

        verify = (config_value('SHOP', 'ACCOUNT_VERIFICATION') == 'EMAIL')

        if verify:
            from registration.models import RegistrationProfile
            user = RegistrationProfile.objects.create_inactive_user(
                username, password, email, send_email=True)
        else:
            user = User.objects.create_user(username, email, password)

        user.first_name = first_name
        user.last_name = last_name
        user.save()

        # If the user already has a contact, retrieve it.
        # Otherwise, create a new one.
        try:
            contact = Contact.objects.from_request(request, create=False)

        except Contact.DoesNotExist:
            contact = Contact()

        contact.user = user
        contact.first_name = first_name
        contact.last_name = last_name
        contact.email = email
        contact.role = 'Customer'
        contact.title = data.get('title', '')
        contact.save()

        if 'newsletter' not in data:
            subscribed = False
        else:
            subscribed = data['newsletter']

        signals.satchmo_registration.send(self, contact=contact, subscribed=subscribed, data=data)

        if not verify:
            user = authenticate(username=username, password=password)
            login(request, user)
            send_welcome_email(email, first_name, last_name)
            signals.satchmo_registration_verified.send(self, contact=contact)

        self.contact = contact

        return contact

class RegistrationAddressForm(RegistrationForm, ContactInfoForm):
    """Registration form which also requires address information."""
    
    def __init__(self, *args, **kwargs):
        super(RegistrationAddressForm, self).__init__(*args, **kwargs)

    def save(self, request=None, **kwargs):
        contact = self.save_contact(request)
        kwargs['contact'] = contact
        
        log.debug('Saving address for %s', contact)
        self.save_info(**kwargs)
                
        return contact

satchmo/templates/account.html
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> 
{% endblock %}

{% block content %}
 <h4>Your Account info</h4>
<p>Welcome, {{ user_data.full_name }}.</p> 
Account options:
<ul>
<li><a href="{% url satchmo_password_change %}">Change your password</a></li>
</ul>
{% endblock %}

satchmo/templates/account_create_form.html
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> ::
Create Account
{% endblock %}

{% block content %}
<h3>Please Enter Your Account Information</h3>

{% if form.has_errors %}
<h2>Please correct the following error{{ form.error_dict|pluralize }}:</h2>
{% endif %}

<table>
<form method="post" action=".">


    <tr><td><label for="id_email">Email Address:</label></td> <td>{{ form.email }}</td></tr>
    <tr><td></td><td>{% if form.email.errors %}*** {{ form.email.errors|join:", " }}{% endif %}</td></tr>

    <tr><td><label for="id_first_name">First Name:</label></td><td> {{ form.first_name }}</td></tr>
    <tr><td></td><td>{% if form.first_name.errors %}*** {{ form.first_name.errors|join:", " }}{% endif %}</td></tr>

    <tr><td><label for="id_contents">Last Name:</label></td><td> {{ form.last_name }}</td></tr>
    <tr><td></td><td>{% if form.last_name.errors %}*** {{ form.last_name.errors|join:", " }}{% endif %}</td></tr>

    <tr><td><label for="id_password">Your password:</label></td><td> {{ form.password }}</td></tr>
    <tr><td></td><td>{% if form.password.errors %}*** {{ form.password.errors|join:", " }}{% endif %}</td></tr>

    <tr><td><label for="id_password2">Confirm password:</label></td><td> {{ form.password2 }}</td></tr>
    <tr><td></td><td>{% if form.password2.errors %}*** {{ form.password2.errors|join:", " }}{% endif %}</td></tr>

	<tr><td><label for="id_newsletter">Newsletter:</label></td><td> {{ form.newsletter }}</td></tr>
	<tr><td></td><td>{% if form.newsletter.errors %}*** {{ form.newsletter.errors|join:", " }}{% endif %}</td></tr>

<tr><td></td><td><input type="submit" value="Create Account"/></td></tr>
</form>
</table>
{% endblock %}

satchmo/templates/base_satchmo.html
{% extends "base.html" %}
{# override this template if you want your shop template to be different than your base template #}

satchmo/templates/checkout_confirm-paypal.html
{% load satchmo.currency_filter %}
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> ::
Checkout
{% endblock %}

{% block content %}
<h3>Checkout</h3>
<div id="checkoutprogress">
<ul>
    <li class="first"><a href="{% url satchmo_checkout-step1 %}">Ship/Bill</a></li>
    <li><a href="{% url satchmo_checkout-step2 %}">Payment</a></li>
    <li class="active">Confirmation</li>
</ul>
</div>
{% if errors %}
    <h3>The following error was returned while trying to process your card.  Please correct and resubmit</h3>
    {{ errors }}
{% else %}
    <h3>Please validate the following information, then submit your order.</h3>
{% endif %}
<h4>Items Ordered</h4>
{% for item in order.orderitem_set.all %}
{{ item }} - {{item.unitPrice|currency}} x {{item.quantity}} = {{item.lineItemPrice|currency}}<br/>
{% endfor %}

<h4>Contact Information</h4>
{{ order.contact.full_name }}<br/>
{{ order.contact.email }}<br/>
{{ order.contact.primary_phone.phone }}<br/>

<h4>Billing Information</h4>
{{ order.fullBillStreet }}<br/>
{{ order.billCity }} <br/>
{{ order.billState }}<br/>
{{ order.billPostalCode }}<br/>
{{ order.billCountry }}<br/>

<h4>Shipping Address</h4>
{{ order.fullShipStreet }}<br/>
{{ order.shipCity }}<br/>
{{ order.shipState }}<br/>
{{ order.shipPostalCode }}<br/>
{{ order.shipCountry }}<br/>
<h4>Shipping Method</h4>
{{ order.shippingDescription }}<br/>
{{ order.shippingMethod }} <br/>
{{ order.shippingCost|currency }} <br/>

<h4>Total</h4>
{% if order.discount %}
    Discount - {{order.discount|currency}}<br/>
{% endif %}
Shipping + {{order.shippingCost|currency}}<br/>
{% if order.tax %}
    Tax + {{order.tax|currency}}<br/>
{% endif %}
Total = {{order.total|currency}}<br/>

<h4>Payment</h4>
Your payment will be processed through PayPal.

<form action="{{ post_url }}" method="post">
<input type="hidden" name="cmd" value="_cart" />
<input type="hidden" name="upload" value="1" />
<input type="hidden" name="business" value="{{ business }}" /> 
<input type="hidden" name="currency_code" value="{{ currency_code }}" />
<input type="hidden" name="no_shipping" value="1" />
<input type="hidden" name="return" value="{{ return_address }}" />
{% for item in order.orderitem_set.all %}
<input type="hidden" name="item_name_{{forloop.counter}}" value="{{item}}" />
<input type="hidden" name="amount_{{forloop.counter}}" value="{{item.unitPrice}}" />
<input type="hidden" name="quantity_{{forloop.counter}}" value="{{item.quantity}}" />
{% endfor %}
<input type="hidden" name="shipping_1" value="{{order.shippingCost}}" />
<input type="hidden" name="tax_cart" value="{{order.tax}}" />
<input type="submit" value="Purchase Items" />
</form>

{% endblock %}

satchmo/templates/checkout_confirm.html
{% load satchmo.currency_filter %}
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> ::
Checkout
{% endblock %}

{% block content %}
<h3>Checkout</h3>
<div id="checkoutprogress">
<ul>
    <li class="first"><a href="{% url satchmo_checkout-step1 %}">Ship/Bill</a></li>
    <li><a href="{% url satchmo_checkout-step2 %}">Payment</a></li>
    <li class="active">Confirmation</li>
</ul>
</div>
{% if errors %}
    <h3>The following error was returned while trying to process your card.  Please correct and resubmit</h3>
    {{ errors }}
{% else %}
    <h3>Please validate the following information, then submit your order.</h3>
{% endif %}
<h4>Items Ordered</h4>
{% for item in order.orderitem_set.all %}
{{ item }} - {{item.unitPrice|currency}} x {{item.quantity}} = {{item.lineItemPrice|currency}}<br/>
{% endfor %}

<h4>Contact Information</h4>
{{ order.contact.full_name }}<br/>
{{ order.contact.email }}<br/>
{{ order.contact.primary_phone.phone }}<br/>

<h4>Billing Information</h4>
{{ order.fullBillStreet }}<br/>
{{ order.billCity }} <br/>
{{ order.billState }}<br/>
{{ order.billPostalCode }}<br/>
{{ order.billCountry }}<br/>

<h4>Shipping Address</h4>
{{ order.fullShipStreet }}<br/>
{{ order.shipCity }}<br/>
{{ order.shipState }}<br/>
{{ order.shipPostalCode }}<br/>
{{ order.shipCountry }}<br/>
<h4>Shipping Method</h4>
{{ order.shippingDescription }}<br/>
{{ order.shippingMethod }} <br/>
{{ order.shippingCost|currency }} <br/>

<h4>Total</h4>
{% if order.discount %}
    Discount - {{order.discount|currency}}<br/>
{% endif %}
Shipping + {{order.shippingCost|currency}}<br/>
{% if order.tax %}
    Tax + {{order.tax|currency}}<br/>
{% endif %}
Total = {{order.total|currency}}<br/>

<h4>Payment</h4>
Your {{ order.CC.creditType }} card ending in 
{{ order.CC.displayCC}} will be charged - {{order.total|currency}}

<form method="post" action=".">
<input type="hidden" name="Process" value="True">
<input type="submit" value="Purchase Items"/>
</form>

{% endblock %}

satchmo/templates/checkout_empty_cart.html
{% extends "base.html" %}


{% block navbar %}
<a href="{{shop_base}}/">Home</a> ::
Checkout
{% endblock %}

{% block content %}
<h3>Checkout</h3>

<p>Your cart is empty.  Please add some items to your cart, then complete the checkout process.</p>

{% endblock %}

satchmo/templates/checkout_pay_ship-paypal.html
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> ::
Checkout
{% endblock %}

{% block content %}
<h3>Checkout</h3>
<div id="checkoutprogress">
<ul>
    <li class="first"><a href="{% url satchmo_checkout-step1 %}">Ship/Bill</a></li>
    <li class="active">Payment</li>
    <li>Confirmation</li>
</ul>
</div>
<h4>Please complete the following information in order to submit your order.</h4>
{% if form.has_errors %}
<h2>Please correct the following error{{ form.error_dict|pluralize }}:</h2>
{% endif %}

<table>
<form method="post" action=".">

    <tr><td><h4>Discounts</h4></td></tr>
    <tr><td><label for="id_discount">Discount code</label></td><td> {{ form.discount }}</td></tr>
    <tr><td></td><td>{% if form.discount.errors %}*** {{ form.discount.errors|join:", " }}{% endif %}</td></tr>
    
    <tr><td><h4>Shipping Information</h4></td></tr>
    </table>
    <div id="shipping">
    <label for="id_shipping">Please choose your preferred shipping method</label>{{ form.shipping}}
    {% if form.shipping.errors %}*** {{ form.shipping.errors|join:", " }}{% endif %}
    </div>
    <input type="submit" value="Confirm"/>
</form>

{% endblock %}

satchmo/templates/checkout_pay_ship.html
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> ::
Checkout
{% endblock %}

{% block content %}
<h3>Checkout</h3>
<div id="checkoutprogress">
<ul>
    <li class="first"><a href="{% url satchmo_checkout-step1 %}">Ship/Bill</a></li>
    <li class="active">Payment</li>
    <li>Confirmation</li>
</ul>
</div>
<h4>Please complete the following information in order to submit your order.</h4>
{% if form.has_errors %}
<h2>Please correct the following error{{ form.error_dict|pluralize }}:</h2>
{% endif %}

<table>
<form method="post" action=".">

    <tr><td><h4>Payment Information</h4></td></tr>
    
    <tr><td><label for="id_credit_type">Type of credit card</label></td> <td>{{ form.credit_type }}</td></tr>
    <tr><td></td><td>{% if form.credit_type.errors %}*** {{ form.credit_type.errors|join:", " }}{% endif %}</td></tr>

    <tr><td><label for="id_credit_number">Credit card number</label></td><td> {{ form.credit_number }}</td></tr>
    <tr><td></td><td>{% if form.credit_number.errors %}*** {{ form.credit_number.errors|join:", " }}{% endif %}</td></tr>

    <tr><td><label for="id_month_expires">Expiration date</label><label for+"id_year_expires"></label></td><td> {{ form.month_expires }} {{form.year_expires}}</td></tr>
    <tr><td></td><td>{% if form.year_expires.errors %}*** {{ form.year_expires.errors|join:", " }}{% endif %}</td></tr>

    <tr><td><label for="id_ccv">CCV</label></td><td> {{ form.ccv}}</td></tr>
    <tr><td></td><td>{% if form.ccv.errors %}*** {{ form.ccv.errors|join:", " }}{% endif %}</td></tr>
    
    <tr><td><h4>Discounts</h4></td></tr>
    <tr><td><label for="id_discount">Discount code</label></td><td> {{ form.discount }}</td></tr>
    <tr><td></td><td>{% if form.discount.errors %}*** {{ form.discount.errors|join:", " }}{% endif %}</td></tr>
    
    <tr><td><h4>Shipping Information</h4></td></tr>
    </table>
    <div id="shipping">
    <label for="id_shipping">Please choose your preferred shipping method</label>{{ form.shipping}}
    {% if form.shipping.errors %}*** {{ form.shipping.errors|join:", " }}{% endif %}
    </div>
    <input type="submit" value="Confirm"/>
</form>

{% endblock %}

satchmo/templates/checkout_success.html
{% extends "base.html" %}
{% load satchmo.google %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> ::
Checkout
{% endblock %}

{% block content %}
<h4>Success!</h4>
{% endblock %}

{% block google-tracker %}
    {% if enable_google %}
        {% show_tracker %}
        {% show_receipt %}
    {% endif %}
{% endblock %}

satchmo/templates/password_change_done.html
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> 
{% endblock %}

{% block content %}

<h2>Password change successful</h2>

<p>Your password change has been completed.</p>

{% endblock %}

satchmo/templates/password_change_form.html
{% extends "base.html" %}

{% block navbar %}
<a href="{{shop_base}}/">Home</a> 
{% endblock %}

{% block content %}
<h2>Change your password</h2>
<p>For the sake of security, please enter your old password, and then enter your new password twice.</p>

<form action="" method="post">
<p>
	{% if form.old_password.errors %}
		{{ form.old_password.html_error_list }}
	{% endif %}
	<label for="id_old_password">Old password:</label>
	{{ form.old_password }}
</p>
<p>
	{% if form.new_password1.errors %}
		{{ form.new_password1.html_error_list }}
	{% endif %}
	<label for="id_new_password1">New password:</label>
	{{ form.new_password1 }}
</p>
<p>
	{% if form.new_password2.errors %}
		{{ form.new_password2.html_error_list }}
	{% endif %}
	<label for="id_new_password2">Confirm new password:</label>
	{{ form.new_password2 }}
</p>	
	<input type="submit" value= "Change password" />
</form>

{% endblock %}

satchmo/templates/shipping_options.html
{% load i18n %}
{% load satchmo_currency %}
{% if default_view_tax %}{% load satchmo_tax %}{% endif %}
{% if default_view_tax %}{{ taxed_shipping_price }} {{ shipping_tax }}{% else %}{{amount|currency}}{% endif %} : {{ description }}
<br>
{% blocktrans %}Sent via {{ method }} arrives approximately {{ expected_delivery }}.{% endblocktrans %}
<hr>